### ISSUE TITLE
nvm use 32 does not switch to 32-bit version

### ISSUE THREAD

**Issue by ardoramor** [coreybutler/nvm-windows#134]
I have nvm-windows 1.1.0 installed. My version installed is 0.12.9 with both 64 and 32 architectures. I specified the following:

```
nvm use 0.12.9 64
> Now using node v0.12.9 (64-bit)

nvm arch
> System Default: 64-bit.
> Currently Configured: 64-bit.

nvm use 32
> Now using node v0.12.9 (32-bit)

nvm arch
> System Default: 64-bit.
> Currently Configured: 64-bit.

nvm use 0.12.9 32
> Now using node v0.12.9 (32-bit)

nvm arch
> System Default: 64-bit.
> Currently Configured: 32-bit.
```

So, for me, the shorthand `nvm use 32|64` doesn't seem to work.

**Comment by ZaLiTHkA** [comment]
I just ran into this same issue on a Win7 Pro x86 system, though I'm not sure if it's actually related to having both the same version installed as bot 32-bit and 64-bit.. Even after removing all Node versions and only installing the 32-bit, `nvm-windows` was still trying to use the 64-bit version.

After a bit more digging, I noticed my `settings.txt` file had `arch = 64`, which is definitely not correct for my environment. After manually setting this to `32`, my `nvm use` command started working as expected again.

Perhaps there's some part(s) of `nvm-windows` that don't use the architecture specified in the runtime parameters?

**Comment by Flarna** [comment]
I face also a 32/64 bit confusion when switching between versions in case I have 32 an 64 bit variants installed:
```
nvm use 6.2.0 64
Now using node v6.2.0 (64-bit)

node -e console.log(process.arch)
ia32

nvm use 6.2.0 64
Now using node v6.2.0 (64-bit)

node -e console.log(process.arch)
x64
```

I have the feeling that nvm somehow remembers the last used bitness somehow but doesn't reuse it when actually setting a new version.

**Comment by ZaLiTHkA** [comment]
@Flarna, nice catch, but I believe there may be a bit more to this than your message implies. Repeatedly activating the same Node version without specifying the arch level seems to switch the `exe` file consistently each time.

This behaviour can be seen in the following console output:

```
D:\>nvm use 4.4.5
Now using node v4.4.5 (64-bit)

D:\>node -e console.log(process.arch)
x64

D:\>nvm use 4.4.5
Now using node v4.4.5 (64-bit)

D:\>node -e console.log(process.arch)
ia32

D:\>nvm use 4.4.5
Now using node v4.4.5 (64-bit)

D:\>node -e console.log(process.arch)
x64
```

**Comment by Flarna** [comment]
Even if I switch between node versions - not just arch - I face an arch toggle. It seems also that passing the arch to nvm use doesn't change the behavior:
```
C:\>nvm use 4.4.5 64
C:\>node -e console.log(process.arch)
ia32
C:\>nvm use 6.2.0 64
C:\>node -e console.log(process.arch)
ia32
C:\>nvm use 4.4.5 64
C:\>node -e console.log(process.arch)
x64
C:\>nvm use 6.2.0 64
C:\>node -e console.log(process.arch)
x64
C:\>nvm use 4.4.5
C:\>node -e console.log(process.arch)
ia32
C:\>nvm use 6.2.0
C:\>node -e console.log(process.arch)
ia32
C:\>nvm use 4.4.5
C:\>node -e console.log(process.arch)
x64
C:\>nvm use 6.2.0
C:\>node -e console.log(process.arch)
x64
C:\>nvm use 4.4.5
C:\>node -e console.log(process.arch)
ia32
C:\>nvm use 6.2.0
C:\>node -e console.log(process.arch)
ia32
```

**Comment by ZaLiTHkA** [comment]
Ah.. And it gets even more interesting. Hopefully this will be enough information for someone who speaks Go to find and fix the problem.. I don't have any experience with it, so I'm not sure how much more I can do other than help debug behaviour.

**Comment by coreybutler** [comment]
I _think_ I got this fixed in v1.1.1, which was just release a few minutes ago. At this point, I'm unable to recreate the error, so I believe it is fixed. Can someone test the new version to make sure it works on their system?

**Comment by ZaLiTHkA** [comment]
Would we need to do a fresh install with `1.1.1`, or should it still work if `1.1.0` was already installed?

I do see the new version with `nvm version` and I get the new table structure when I run the `nvm list available`, so it does seem to have upgraded correctly, but I still get the exact same behaviour as before with the `nvm use <version>` command..

**Comment by Flarna** [comment]
If I type `nvm use <version>` without specifying the bitness it still switches between 32 and 64 bit.

**Comment by ZaLiTHkA** [comment]
I get the same behaviour as Flarna describes, but only in cases where I have both the 32-bit and 64-bit binaries installed for the same version. Generally speaking I prefer to stick with one or the other though, so I explicitly install both whenever I need to test something like this.

If I remember correctly from my testing yesterday, with only the 32-bit version installed that command throws a "version not installed" error (I forget the exact wording, but if need be I think I can reproduce it to check).

I can't remember off-hand what happens if only the 64-bit version is installed.

**Comment by Flarna** [comment]
I install always 32 and 64 bit variants of the same node versions as I have to verify a native addon.
Meanwhile I'm quite used to this bitness switching so maybe I will even miss it if it get fixed :o).

**Comment by bblanchon** [comment]
Hi,

I too have this problem.
It always switches between 32 and 64, even when I specify the architecture to `nvm use`.

![nvm_bug_32_64](https://cloud.githubusercontent.com/assets/5462433/16683958/9db60f4a-4502-11e6-86e3-20d2c779769b.gif)

**Comment by bblanchon** [comment]
I submitted PR #218 to address this problem.
Binaries are available here: https://github.com/bblanchon/nvm-windows/releases/tag/fix-swap-32-64

**Comment by asdkevinasd123** [comment]
This issue is still persisting in 1.1.7. Is there anyone to workaround it for now?

**Comment by coreybutler** [comment]
A patch for this was merged. It can still be an issue on Windows 7 systems due to inconsistent results returned by the OS. I believe this issue is resolved for Windows 8+. If not, please open a new issue.
