### ISSUE TITLE
Issue with blank spaces in path

### ISSUE THREAD

**Issue by emartinpi** [coreybutler/nvm-windows#41]
Hello! I'm having a problem when i'm trying `nvm use <node_version>`
![captura](https://cloud.githubusercontent.com/assets/10350688/6235190/f138cf60-b6e0-11e4-892c-440d4ca7c78f.JPG)
Sorry for the spanish language in screenshot. It means "c:\Users\Edu" is not recognise as an internal command... bla bla bla.
My user name is "Edu Martin" and my path is "c:\Users\Edu Martin\AppData\Roaming\nvm"
Is it possible to be an error with black spaces in the path?? All settings in my app are standard

**Comment by bholloway** [comment]
+1

**Comment by impaler** [comment]
+1 many windows installs have user names with spaces

**Comment by kirkouimet** [comment]
+1 for this, ran into this same issue with my username

**Comment by kirkouimet** [comment]
So a fix to this is to edit your settings.txt and use the alternate Windows folder naming scheme which does not have spaces, which for my case was:

![2](https://cloud.githubusercontent.com/assets/62191/6793510/a3528b8a-d182-11e4-9d8c-1bcaaee51165.PNG)

**Comment by PureKrome** [comment]
@coreybutler can we please have a fix for this, please please please?

:pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: 

here's a gif to try and co-coerce you...

![](http://i.giphy.com/2NrnzD6zS1Upq.gif)

**Comment by coreybutler** [comment]
My build environment has changed recently/substantially, so the problem is releasing the binaries (I had a really customized build script). I'd be happy to add the fix to the master branch, it would just require building from source.

I have to head to the UK next week, but when I return to the US I'll address this as soon as I can.

**Comment by PureKrome** [comment]
That would be lovely @coreybutler :) Also, maybe we can link the next build (with this patch) to #17 etc?

**Comment by CMaso** [comment]
I was having this problem because it wanted to use "C:\Documents and Settings\(my name)\Application Data\nvm" as the root. So what I did was reinstall nvm, specifying "C:\" as the root instead of the default during the install, so it's now storing all the versions of Node in "C:\nvm", which of course has no spaces in the path. Settings.txt confirms this as the root. I just needed to remember to cd to C:\ before using any of the nvm commands, else it threw an error saying it can't find settings.txt. In my case, since C:\ isn't associated with any one user, when I switch to a version of Node using "nvm use <version>"  it asks me which user account I  want to use to run the program. But it seems to be running fine; I'm getting the "now using node <version>" message.

**Comment by mhchristensen** [comment]
+1  For anyone wanting to do the workaround editting the settings.txt you can try this from command line to get the correct formatted path

cmd /c for %A in ("C:\Users\My Name With Spaces\AppData\Roaming\nvm") do @echo %~sA

**Comment by markbrownsword** [comment]
Installing nvm-windows into Program Files also causes this error. Updating settings.txt as below resolves the issue, but it would be nice to get this fixed, or added to the ReadMe as a 'Gotcha'!

root: C:\PROGRA~1\nvm
path: C:\PROGRA~1\nodejs

**Comment by clmcgrath** [comment]
using a symbolic junction link on windows i found is a suitable workaround to this problem as well 
use something like this 
mklink /J nvm_home "C:\Users\Chris McGrath\AppData\Roaming\nvm"

then up date settings.txt with the junction address

**Comment by codeimpossible** [comment]
So this issue has been open for almost a year. Is nvm-windows dead?

**Comment by coreybutler** [comment]
@codeimpossible - Not dead, I've just had higher life priorities to deal with. I'll post a note about it in gitter.

**Comment by kirkouimet** [comment]
@coreybutler just wanted to let you know I use `nvm-windows` every day and appreciate all of the hard work you put into the project

**Comment by coreybutler** [comment]
@kirkouimet Thanks... thrilled to hear it is helpful!

**Comment by AntiCZ** [comment]
Hi coreybutler, great job with nvm. This is really making my life easier :D

But can you write somewhere info about the space? Something like 

"If you have a space in your user name change default directory used by the installer and choose path without a space."

I have never edit wiki on github. I have a little fear what I can do.

**Comment by coreybutler** [comment]
@AntiCZ - Good idea. I added a [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) page to address this. I'll continue to add to this as neccessary.

**Comment by picss** [comment]
I solve mine using cmd /c for %A in ("C:\Users\My Name With Spaces\AppData\Roaming\nvm") do @echo %~sA by @emartinpi  thanks a lot :+1:

**Comment by espoelstra** [comment]
Without a space in `$env:USERPROFILE` are people still having problems with the nodejs path having spaces in Program Files? I'm not seeing the same behavior on my Windows 2012R2 VM. I'm going to test with a user with a space in the name to see if that is causing a cascading failure of some sort. It would be great to get some OS versions and which cmd prompt you are using (PowerShell/CMD/Bash4Windows/GitBash).

**Comment by SamHard** [comment]
I had almost this same issue, except my user name has an ampersand (&) instead of a space.  In this situation, using the alternate folder name didn't help, because even the short name still has the ampersand.  However, creating a symbolic link, as @clmcgrath suggested, was a good workaround for me.

**Comment by thematho** [comment]
I just solve this using the short name notation when installing nvm
```
D:\PROGRA~1\nvm
D:\PROGRA~1\nodejs
```

**Comment by kyleshrader** [comment]
Just install it to C:\programs\nvm

**Comment by dragon788** [comment]
Also why the NVM package on Chocolatey is using the C:\ProgramData\nvm path since that is the Program Files equivalent of "All Users" but without spaces.

**Comment by jkutianski** [comment]
The problem is the path expansion, but can be solved with a simple workaround.
On **settings.txt** add quotations marks on both path to escape the spaces.
```
root: "C:\Users\Path With Spaces\AppData\Roaming\nvm"
path: "C:\Program Files\nodejs"
```

**Comment by bstaruk** [comment]
This is still an issue, almost 2 years after it was reported.

**Comment by ryan-mcguire** [comment]
This can be worked around by using alternate names for folders or files with spaces.  For instance, I have nvm installed in "C:\Programs Files\nvm".  Go to the folder above the ones with the space and use the /X option to get a directory listing with antique 8.3 names:

> cd \
> dir /X

I got a line that looks like...
> 2/15/2017  03:44 PM    \<DIR\>   PROGRA~1     Program Files

Then just edit the settings.txt file (in \Programs Files\nvm in my case) and edit the offending folder name:

root: C:\Progra\~1\nvm
path: C:\Progra\~1\nodejs

(This is the same solution @markbrownsword gave over a year ago, but his message got a bit misformatted by the markdown engine.)

**Comment by enaldick** [comment]
# windows

> move to path there without whitespace 

or 

>running cmd as administrator   
and then mklink it to the new path there without whitespace.

**Comment by MadaraUchiha** [comment]
@coreybutler Any news regarding this issue? I just got hit with it. I'm willing to PR it if you tell me what to look for :)

**Comment by coreybutler** [comment]
I've just pre-released (v1.1.6)[https://github.com/coreybutler/nvm-windows/releases/tag/1.1.6], which leverages a new path management system in Go 1.8.3. All of my local tests are working with spaces and special characters in paths, but I can only test on an English install of Windows 10 at the moment. I'm hoping a few folks who have experienced this issue can test it out. Assuming the issue is resolved, I'll release 1.1.6 officially as a fix.

**Comment by clmcgrath** [comment]
TBH i haven't had this issue happen in a number of releases now ,  been pretty smooth for  a year or so now

**Comment by coreybutler** [comment]
@clmcgrath - glad to hear it! 

For clarification, my primary curiosity is with non-English installations, which were producing some hidden characters Go recognized as a string terminator.... it was cutting the path off prematurely.

**Comment by chillerfx** [comment]
Still doesn't work. I tried changing setting.txt that did't help either.

**Comment by coreybutler** [comment]
@chillerfx - Do any commands run, or is it just `nvm use` failing? Also, what locale is your environment (non-English?)

**Comment by nelli02** [comment]
On my windows 7 OS, 'nvm list' works but 'nvm use <version>' does not work. My locale is English.

**Comment by Zakini** [comment]
My setup:
> nvm v1.1.6
> Windows 10 Pro (version 1703, build 15063.540)
> Locale: English (UK)

Still having this issue. `nvm install latest` works but `nvm use 8.4.0` fails. My username has a space in it like "John Smith" and the error I get is `exit status 1: 'C:\Users\John' is not recognized as an internal or external command, operable program or batch file.`

Everything (list, use, install) works when edit my settings file as @ryan-mcguire suggests though.

**Comment by dragon788** [comment]
Can those having issues run `nvm root` and report what is printed?

**Comment by JeffUtz** [comment]
nvm root: `C:\Users\Jeff Utz\AppData\Roaming\nvm`

My setup:

> nvm v1.1.6
> Windows 10 Pro (1703, build 15063.540)
> Locale: English (US)

All commands work with the exception of `nvm use` ... `nvm on` will enable nvm but then give the `exit status 1` error

**Comment by gabialex** [comment]
Try to use the shortened path name. 
To find the shortened path:
C:\Users
dir /x

![image](https://user-images.githubusercontent.com/12614380/30240728-8a9d1ab6-957e-11e7-84cb-fb049088c248.png)

**Comment by psiddharth709** [comment]
![error](https://user-images.githubusercontent.com/25383528/30782627-429c4850-a153-11e7-9e82-a3a1cb459445.png)


how to solve error ??please share your ans..

**Comment by coreybutler** [comment]
@psiddharth709 - please stop posting the same question in multiple issues.

**Comment by XepherX** [comment]
+1 on this issue. ![Image of repro](https://i.imgur.com/A9KLLfl.png)
+1 to @kirkouimet for the clever workaround

**Comment by angrycodepoet** [comment]
I dig the c:\nvm solution. I like having my stuff, esp. on Windows in a folder I can easily find it (c:\xammp is my apache server). Did it that way and all is well. Thanks for the hard work.

**Comment by Eccenux** [comment]
@coreybutler You can test the issue by installing `nvm` in any folder with space character. E.g. in `C:\Program files\nvm` (the error is as shown by XepherX above -- "'C:\Program' is not recognized...").

My guess is the problem is with running `elevate.cmd` with `exec.Command`. I'm not sure because I don't know how to debug Go. But when I rename `elevate.cmd` I get an error about missing file and when I restore `elevate.cmd` I get the error with "'C:\Program' is not recognized..."

So this does not seem to be a problem with a character set. And the problem occurs both in Windows 7 and Windows 10. Even if `cmd` is already elevated (Run as administrator).

**Comment by davidrosevear** [comment]
@coreybutler Unfortunately, still the same issue for me as with everyone else in this issue, even using the 1.1.6 pre-release version.

**Comment by coreybutler** [comment]
Thanks everyone! My apologies for the delays in getting a new version out.... I'm still swamped (and hiring).

@Eccenux - you may be onto something there. I'll review the `elevate.cmd`. Go is compiled, so debugging happens pre-build. I think the elevate command is a more likely culprit, but will confirm first chance I get.

**Comment by seanpoulter** [comment]
I've had the same issue as @davidrosevear. `nvm install` worked with 1.1.6, but `nvm use` did not. Let me know if you'd like me to have a look @coreybutler.

**Comment by korneliuskristianr** [comment]
I still got this issue

**Comment by coreybutler** [comment]
@seanpoulter and anyone else interested in helping out....

I have a great problem - _lots_ of new clients flowing into my consulting company. The problem: abnormally little time to work on anything else. Any extra eyes that could take a look at this issue would be greatly appreciated. I still haven't had a chance to look into @Eccenux's suggestion re: `elevate.cmd`, but I think that's the starting point. 1.1.6 has a bunch of native go character escaping, so my gut says the problem isn't with Go... but the elevate command doesn't get tested with the rest of the code.

**Comment by seanpoulter** [comment]
Congrats! That's a great problem to have indeed.

Let's look at a community solution and PR for this one while @coreybutler's busy. I've got a big PR to review on another repo (vscode-jest), so it'll be a bit before I can dive into this one myself.

**Comment by hlbglobal** [comment]
those shortented file versions don't work and neither does installing R in a  path with a space
How can we fix these problems.  If we install R in a different directory will  it still  use the path varaible for anything else?

**Comment by s-h-a-d-o-w** [comment]
As it's been a while since the last release here, I decided to publish one containing the fix I submitted just before on my fork in the meantime:
https://github.com/s-h-a-d-o-w/nvm-windows/releases/tag/1.1.7

**Comment by tonysamperi** [comment]
I resolved by moving it to C:\nvm, but I'd like to know if any fixes is planned....

**Comment by ctsstc** [comment]
Thanks @s-h-a-d-o-w just installed your version coming from `v 1.1.6` with my username being "Cody Swartz" in my path I was getting the same error everyone else was getting and your fix looks clean and to the point. Now `nvm use` works! 🎉

**Comment by jtcotton63** [comment]
I just downloaded and installed nvm for windows for the first time today and ran into this issue. I'm running version 1.1.7. Is there something I'm missing here? Shouldn't this have been fixed for v1.1.6 and later?

**Comment by edenprojectde** [comment]
Also having this problem. Making the whole thing pretty much not usable.

**Comment by felipexw** [comment]
The bug still remains. It's not solved. Using nvm 1.17

**Comment by Laslo89** [comment]
> root: C:\PROGRA1\nvm
> path: C:\PROGRA1\nodejs
The config above mentioned earlier in this thread is wrong, or does not work for me at least ... ;)
For anyone who stumbles upon this issue.
When you have installed nvm and nodejs in C:\Program Files just use the following config in settings.txt and it should work. 

root: C:\PROGRA~1\nvm
path: C:\PROGRA~1\nodejs

**Comment by JeremiGendron** [comment]
@Laslo89 has the right answer, replacing the space with ~ works well

**Comment by morgyface** [comment]
> So a fix to this is to edit your settings.txt and use the alternate Windows folder naming scheme which does not have spaces, which for my case was:
> 
> ![2](https://cloud.githubusercontent.com/assets/62191/6793510/a3528b8a-d182-11e4-9d8c-1bcaaee51165.PNG)
> 
> (settings.txt is in AppData\Roaming\nvm by default)

A quick note for those lacking general tech ability like me. If you use `dir *. /x` in the command prompt it will list out the directories within the current location giving you the **8.3 form** name in the middle column. You can then use this to change the settings as outlined above. Though, as mentioned earlier, `Program Files` becomes `PROGRA~1`.

**Comment by psiddharth709** [comment]
which website provide ionic related latest tutorial.?  please tell me.....

>

**Comment by julian-becker** [comment]
how is this issue still not fixed?! If it is a regression in 1.1.7, maybe think about adding a few integration/unit/regression tests to cover the not-so-uncommon case of spaces in windows (or linux for that matter) path names before releasing it...

Do you guys need support on this or is there already someone actively working on this?

**Comment by seanpoulter** [comment]
@julian-becker, first off I'd like to call you out your aggressive start:
> how is this issue still not fixed?!

It's rude. Folks in the open source community don't owe you any of their time or attention. What makes your spare time any more precious than the maintainers, or ours? It seems like you didn't spend the time to see that @coreybutler has already answered your question [here](https://github.com/coreybutler/nvm-windows/issues/41#issuecomment-364601100):
> I have a great problem - lots of new clients flowing into my consulting company. The problem: abnormally little time to work on anything else.
You also missed the solution and fork that @s-h-a-d-o-w shared.

Second, -- you've got a great game plan for how this **should** be done. **Do it!** If you've got the time, everyone watching this issue will appreciate it being fixed. Have a look at what @s-h-a-d-o-w has done, add the tests, get a PR going, and reach out here for help with the code-review. Someone is self-interested enough to help get'r done. Good luck, and reach out here if you need some help! 👏

**Comment by s-h-a-d-o-w** [comment]
> get a PR going

To avoid possible confusion and work being done twice, I'd like to note that my fix was [already merged](https://github.com/coreybutler/nvm-windows/pull/355), it's just a matter of actually releasing it.

**Comment by seanpoulter** [comment]
Perfect! I didn't have that much time to read either. 😆

**Comment by kstreichergb** [comment]
@s-h-a-d-o-w Just ran into this problem again, any idea when it will be released?

**Comment by s-h-a-d-o-w** [comment]
@coreybutler Would you mind linking to the release in my fork in a final post here and then locking this thread? I don't think that there is a need to discuss it further...

**Comment by scote** [comment]
@coreybutler may it be possible to do the release?

**Comment by sittingbool** [comment]
Please release this :)

**Comment by AndersSchultz** [comment]
Using the fork released by s-h-a-d-o-w (see link above) worked for me as the only thing. Big thanks!

**Comment by coreybutler** [comment]
I've linked to @s-h-a-d-o-w 's release in [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#spaces-in-pathnamesinstallation-root). 

Sorry it is taking me so long to cut a release. I know it seems straightforward, but time has been brutal for me. Maybe I'll write about it someday.

**Comment by fullsteack** [comment]
1.In cmd, go to your home directory and type dir/x to see the shortened name for this folder
2.Then replace your user name with this shortened name in the setting.txt
3.It works

**Comment by vineethm1627** [comment]
> +1 For anyone wanting to do the workaround editting the settings.txt you can try this from command line to get the correct formatted path
> 
> cmd /c for %A in ("C:\Users\My Name With Spaces\AppData\Roaming\nvm") do @echo %~sA

Thanks a lot this thing saved my life.

**Comment by Swarag-N** [comment]
### Solved!!
For someone who is not able to work with ~1 method by @kirkouimet  (Thanks mate)
Open CMD go to the Users folder and Get the Shortened Folder name.

and type 

### > `dir\x `

![Annotation 2020-05-25 112714](https://user-images.githubusercontent.com/46181010/82782765-c2d29200-9e7a-11ea-83ed-6173ddd85948.png)

Now later after copying or Noting down the folder name
![Annotation 2020-05-25 113201](https://user-images.githubusercontent.com/46181010/82783088-69b72e00-9e7b-11ea-8715-e721d7961c8c.png)

Hope it helps

**Comment by wafakhan9232** [comment]
> ### Solved!!
> For someone who is not able to work with ~1 method by @kirkouimet (Thanks mate)
> Open CMD go to the Users folder and Get the Shortened Folder name.
> 
> and type
> 
> ### > `dir\x `
> ![Annotation 2020-05-25 112714](https://user-images.githubusercontent.com/46181010/82782765-c2d29200-9e7a-11ea-83ed-6173ddd85948.png)
> 
> Now later after copying or Noting down the folder name
> ![Annotation 2020-05-25 113201](https://user-images.githubusercontent.com/46181010/82783088-69b72e00-9e7b-11ea-8715-e721d7961c8c.png)
> 
> Hope it helps

Thank you everyone that suggested the settings.txt solution but specially Swarag-N for such a thorough explanation. I am glad I landed here and not changed my user profile folder. 
Thanks

**Comment by sourabh69733** [comment]
Please check this page, it works for me 
https://oclockvn.github.io/2019/04/29/common-issues-nvm-on-windows.html

**Comment by noelsimbolon** [comment]
> 
> 
> So a fix to this is to edit your settings.txt and use the alternate Windows folder naming scheme which does not have spaces, which for my case was:
> 
> ![2](https://cloud.githubusercontent.com/assets/62191/6793510/a3528b8a-d182-11e4-9d8c-1bcaaee51165.PNG)
> 
> (settings.txt is in AppData\Roaming\nvm by default)

This worked for me. Thank you!

**Comment by BrandonEdlin** [comment]
Is there a way for nvm to be installed into program files?  My org has policies set only allowing applications to be installed in there

**Comment by coreybutler** [comment]
@BrandonEdlin yes. You have a choice. Your organization can also create their own installer if they prefer. See [this guide](https://github.com/coreybutler/nvm-windows/wiki#manual-installation).

**Comment by nalonix** [comment]
It's 2025 and am still dealing with this issue, this is odd.

**Comment by 3x10RaiseTo8** [comment]
> It's 2025 and am still dealing with this issue, this is odd. I am on windows 11, and installation works but `nvm use [version] `fails

I faced the same issue. To use `use` or `install` commands, you have to be in an elevated shell. So run as administrator and then use it.

Following this, I wasn't able to use `npm` command, because of some ExecutionPolicy something. In same Administrator Shell (powershell), run `Set-ExecutionPolicy RemoteSigned`.

Check out [Common Issues wiki page.](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues)
