### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by ClusterH** [coreybutler/nvm-windows#700]
**Issue:**
After install `nvm 1.1.8`, `nvm install lts`, it seems installing node 16.13.0.
But when I do `nvm use 16.13.0` or `nvm use lts`, got error like that: `exit status 1: Access is denied`

Tried open `cmd` as administrator, but it does not help

**Comment by ClusterH** [comment]
Tried again reinstall `nvm` and `nvm install 16.13.0`, it worked. but it is really weird, why did not worked with `nvm install lts`

**Comment by quanticle** [comment]
I'm getting the same error with `nvm use latest`, when running PowerShell as a regular user. When I run PowerShell as admin, `nvm use latest` works.

**Comment by erikyuzwa** [comment]
Hitting this lately as well when I want to switch to *any* node version. Had to run my cmd shell as Administrator for it to work

**Comment by robertwt7** [comment]
I'm getting this error as well, was about to open an issue

**Comment by JeffersonUCC** [comment]
same here. Prior to 1.1.8 system would prompt me to grant admin privileges. I think the issue might be `nvm` not using the `elevated.cmd` to get admin status.

**Comment by chaostheory** [comment]
This might be related to this issue, but I was able to install node 16. However, if I try to use npm, then I get hit with the Access Denied error.

**Comment by lawweiliang** [comment]
I am having this problem with my 'Cmder Console' as well.
![image](https://user-images.githubusercontent.com/34936929/144695140-55fc955e-b0ed-4b56-a39f-42768e121c62.png)

Over Command Prompt Administrator, no problem
![image](https://user-images.githubusercontent.com/34936929/144695128-0d7b9579-eaa6-4f9b-a137-e363740f6506.png)

**Comment by onikienko** [comment]
Same issue. Possible it is because v1.1.8 is not code signed. Installing v1.1.7 resolves the issue.

**Comment by hyf510** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by danillolima** [comment]
I tried both v1.1.7 and v1.1.8 and both need to run with administrative privileges to change the versions of node.

**Comment by coreybutler** [comment]
Admin privileges are required (by the operating system) to create the links. If the error states "insufficient privileges", it means exactly that. You need an admin account.

For those of you struggling with `nvm use latest`, `lts`, or `newest` - there was a bug introduced with these aliases. I've fixed this locally and will release it as v1.1.9 very soon.

For those installing a version with _npm_ v5.x.x - there are hard coded issues in some versions of npm that have affected node version managers. See the wiki and search the issues for more details.

I have also reintegrated automatic elevation. This means you will be prompted with the UAC prompt when needed. If you are running in "Developer mode", the prompts are unnecessary and will not be displayed.

These issues have nothing to do with code-signing. However; the next release _will_ be code-signed, thanks to a generous sponsor whose financial contribution made it possible to obtain an extended validation certificate.

I will close this issue when v1.1.9 is released (this week).

**Comment by erikyuzwa** [comment]
thanks for moving on this @coreybutler - appreciate it 🙇

**Comment by coreybutler** [comment]
[v1.1.9](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9) has been released.

**Comment by matthiasthieroff** [comment]
Hey Corey,
thanks for your great work. Unfortunately the "access is denied" error is still present with v1.1.9 on powershell 7.2. There is also no automatic elevation happening. I just had a fresh installation on a new Windows 10 system.

**Comment by quckslvr** [comment]
He @coreybutler same thing too

Did `nvm install 16.9.1` and when I do `nvm use 16.9.1` it prompt `exit status 1: Access is denied.`

I followed the readme to delete node.js delete the files mention and still experience the issue.

on the other on admin it works but not on my user.

**Comment by MattHoneycutt** [comment]
Same issue here, fresh install on Win 11.  I downgraded to 1.1.7, and everything works great.

**Comment by diogoeichert** [comment]
Same here. After removing 1.1.9 and installing 1.1.7 (without Administrator privileges) everything works fine, apart from the `lts` alias:
```
Microsoft Windows [Version 10.0.19044.1415]
(c) Microsoft Corporation. All rights reserved.

C:\Users\User>nvm version
1.1.7

C:\Users\User>nvm install lts
lts.0.0
Node.js vlts.0.0 is only available in 32-bit.

C:\Users\User>nvm install 16
16.0.0
Downloading node.js version 16.0.0 (64-bit)...
Complete
Creating C:\Users\User\AppData\Roaming\nvm\temp

Downloading npm version 7.10.0... Complete
Installing npm v7.10.0...

Installation complete. If you want to use this version, type

nvm use 16.0.0

C:\Users\User>nvm use 16.0.0
Now using node v16.0.0 (64-bit)
```

**Comment by ojintoad** [comment]
This item covers some things people are posting here and likely should be followed instead: https://github.com/coreybutler/nvm-windows/issues/767

**Comment by afanfian** [comment]
Who knows someone can help, because I've tried several times still can't use the node js version through nvm, thank you
**Problem**
![image](https://user-images.githubusercontent.com/82325182/220523400-0a4bd33e-d908-451d-8f7c-7212c3097837.png)
**Path NVM**
![image](https://user-images.githubusercontent.com/82325182/220523521-8c66b299-d967-43ab-8139-e76f03ac6bf7.png)
