### ISSUE TITLE
npm ERR! Unexpected token '.'

### ISSUE THREAD

**Issue by yassine-klilich** [coreybutler/nvm-windows#871]
**Issue:**
Can't init npm, I'm getting (npm ERR! Unexpected token '.') when I run command `npm init`

**How To Reproduce:**
1. Open CMD
2. Type `npm init`
3. Press Enter

![image](https://user-images.githubusercontent.com/24640070/198651118-6153fd51-adac-45c3-9d6d-229da3beddcf.png)

**Logs**
[2022-10-28T14_38_02_332Z-debug-0.log](https://github.com/coreybutler/nvm-windows/files/9889302/2022-10-28T14_38_02_332Z-debug-0.log)
[2022-10-28T14_38_03_129Z-debug-0.log](https://github.com/coreybutler/nvm-windows/files/9889304/2022-10-28T14_38_03_129Z-debug-0.log)

I'm using:
NVM: 1.1.9
NPM: 8.19.0
Node.js: v18.12.0

**Comment by coreybutler** [comment]
You have a non-standard version of npm. Node 18.12.0 ships with npm 8.19.2, not 8.19.0.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/770982/198697964-a571902a-1ecc-4852-9e14-5fe4a7443fb2.png">

You may just need to uninstall/reinstall node 18.12.0 to assure you have the appropriate version of npm.

**Comment by yassine-klilich** [comment]
Thank you @coreybutler, I will check it Monday, and a comment if it worked. Thank you again.

**Comment by dhroiden** [comment]
@coreybutler issue seems to persist even with 8.19.2
![image](https://user-images.githubusercontent.com/5513031/199366939-4e2a33ef-6d71-44b3-8962-7906ac61fffb.png)

**Comment by coreybutler** [comment]
@dhroiden - you may want to upgrade nvm to a more recent version. v1.1.10 brought back UAC prompts (i.e. it's more aligned with the v1.1.7 release you're using).

<img width="500" alt="image" src="https://user-images.githubusercontent.com/770982/199385908-743389df-6e26-4331-a713-dae151147250.png">

Alternatively, you may need to reinstall node v18.12.0. npm can be finicky about how it is setup/uninstalled, and this is definitely an npm issue that NVM4W merely tries to work around.

**Comment by yassine-klilich** [comment]
@coreybutler I updated everything, but still getting the same issue

![image](https://user-images.githubusercontent.com/24640070/199434248-5c2f603c-f29b-451c-bd35-629df7a13d83.png)

**Comment by coreybutler** [comment]
@yassine-klilich - did you uninstall/reinstall Node 18.12.0 or run the [gist](https://gist.github.com/ddomen/ac17ef3edb15712130c3db3d47e4b377)? If you just upgraded NVM4W or npm, it won't have any affect. The root of the problem is in npm. Sometimes npm creates text files instead of symbolic links to directories, causing this error. The previously mentioned gist is supposed to track that down and correct it within npm. Some people find it easier to reinstall Node (to force reinstallation of npm). Others prefer to manually replace npm. Regardless, those faulty symlinks need to be corrected.

Additionally, running `npm i` is not the same as running `npm init`. Running `npm i` alone will fail if there is no package.json file.

**Comment by yassine-klilich** [comment]
@coreybutler - Worked. I uninstalled NVM and installed it again and installed Node again, and it worked fine now.

**Comment by albertgarcias** [comment]
Hi, 
I'm facing the same issue with **npm install**, I downloaded 3 node versions today and all have the same issue 18.12.0, 18.10.0 and 16.18.0. If I go back to a previously downloaded version I can build and all goes fine. With the newly downloaded versions  npm complains about the unexpected token and can't communicate with nexus/artifactory and fails the builds.

```
C:\>npm -version
npm WARN config `_auth`, `_authToken`, `username` and `_password` must be scoped to a registry. see `npm help npmrc` for more information.
npm WARN config `_auth`, `_authToken`, `username` and `_password` must be scoped to a registry. see `npm help npmrc` for more information.
8.19.2
```
I've updated to latest nvm 1.1.10 re-installed versions but same issue.
I've runned the e [gist](https://gist.github.com/ddomen/ac17ef3edb15712130c3db3d47e4b377) with  `node npm_windows_fix.js`  but same error.

**Comment by albertgarcias** [comment]
yes, custom npm registry but the error internal error looked similar. The strange thing is that when I switch to another node version with nvm use it works. When I use the one's downloaded today it fails.

```
34 verbose stack C:\Users\garalber\AppData\Roaming\nvm\v16.18.0\node_modules\npm\node_modules\libnpmfund:1
34 verbose stack ../workspaces/libnpmfund
34 verbose stack ^
34 verbose stack
34 verbose stack SyntaxError: Unexpected token '.'
34 verbose stack     at Object.compileFunction (node:vm:360:18)
34 verbose stack     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
34 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1119:27)
34 verbose stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
34 verbose stack     at Module.load (node:internal/modules/cjs/loader:1033:32)
34 verbose stack     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
34 verbose stack     at Module.require (node:internal/modules/cjs/loader:1057:19)
34 verbose stack     at require (node:internal/modules/cjs/helpers:103:18)
34 verbose stack     at Object.<anonymous> (C:\Users\garalber\AppData\Roaming\nvm\v16.18.0\node_modules\npm\lib\utils\reify-output.js:16:38)
34 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1155:14)
35 verbose cwd C:\D\Projects\LPA\lpa-c-gui
36 verbose Windows_NT 10.0.19042
37 verbose node v16.18.0
38 verbose npm  v8.19.2
39 error Unexpected token '.'
40 verbose exit 1
41 timing npm Completed in 110ms
42 verbose code 1
43 error A complete log of this run can be found in:
43 error     C:\Users\garalber\AppData\Local\npm-cache\_logs\2022-11-02T14_36_43_138Z-debug-0.log
```

I will try to re-install as suggested. 

thank you

**Comment by yassine-klilich** [comment]
@albertgarcias Hope re-installing NVM work for you, because it worked for me. And I tried to run `node npm_windows_fix.js` but I got some errors too.
@coreybutler thank you so much for your support, I appreciate it my friend.
I will close this issue since I fixed it by re-installing NVM.

**Comment by Entroper** [comment]
Hi, I'm still having this issue.  Using nvm 1.1.10, node 18.12.1, npm 8.19.2.

I tried uninstalling and reinstalling nvm.  I also tried running the gist, all it does is print DONE.
